require "mosukiton.plugins"
require "mosukiton.options"
require "mosukiton.keymaps"
require "mosukiton.colorscheme"
require "mosukiton.telescope"
require "mosukiton.projections"
require "mosukiton.autocmds"
require "mosukiton.custom-commands"
