require "local.plugins"
require "local.options"
require "local.keymaps"
require "local.colorscheme"
require "local.telescope"
require "local.projections"
require "local.autocmds"
require "local.custom-commands"
